# Generated by Django 2.2.10 on 2021-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=10, null=True)),
                ('member_phone', models.CharField(max_length=20, null=True)),
                ('member_team', models.IntegerField()),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Race_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=30)),
                ('m_content', models.TextField(null=True)),
                ('m_signup_requset', models.TextField(null=True)),
                ('m_work_request', models.TextField(null=True)),
                ('m_race', models.IntegerField()),
            ],
            options={
                'db_table': 'race_message',
            },
        ),
        migrations.CreateModel(
            name='Race_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'race_name',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(max_length=30)),
                ('T_intro', models.TextField()),
                ('T_leader', models.CharField(max_length=10)),
                ('T_phone', models.CharField(max_length=20)),
                ('T_state', models.CharField(max_length=20, null=True)),
                ('T_honor', models.CharField(max_length=20, null=True)),
                ('T_message', models.IntegerField()),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
