# Generated by Django 2.2.10 on 2021-08-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20210819_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_team',
        ),
        migrations.AddField(
            model_name='member',
            name='invite_state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='T_remark',
            field=models.TextField(null=True),
        ),
    ]
