# Generated by Django 2.2.10 on 2021-08-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20210819_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='message_id',
            new_name='team_id',
        ),
    ]
