# Generated by Django 2.2.10 on 2021-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20210830_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race_name',
            name='end_date',
            field=models.DateTimeField(default='2021-9-1 00:00:00'),
        ),
        migrations.AlterModelTable(
            name='honor',
            table='honor',
        ),
    ]
