# Generated by Django 2.2.10 on 2021-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_auto_20210830_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race_name',
            name='end_date',
            field=models.DateTimeField(default='2001-10-09 00:00:00'),
        ),
        migrations.AlterField(
            model_name='race_name',
            name='start_date',
            field=models.DateTimeField(default='2001-10-09 00:00:00'),
        ),
    ]
