# Generated by Django 2.2.10 on 2021-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('type', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('context', models.TextField()),
            ],
        ),
    ]
